[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install -r requirements.txt",
  "source /opt/venv/bin/activate && python -m spacy download en_core_web_sm"
]

[start]
cmd = "source /opt/venv/bin/activate && cd Backend && python start_secure.py"

